#!/usr/bin/python
#
# Copyright (C) 2012-2013 Owen Derby (ocderby@gmail.com)
# Copyright (C) 2021 Eva Lond (2evalond@gmail.com)
#
# This file is part of pbots_calc.
#
# pbots_calc is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# pbots_calc is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# pbots_calc in a file in teh toplevel directory called "GPLv3".  If not, see
# <http://www.gnu.org/licenses/>.
#
import os

import struct
is64bit = struct.calcsize("P") * 8 == 64

Import("env")
calc_prog = env.Program(
    target="calculator", source=["calculator.c"], LIBS=["pbots_calc", "poker-eval_x64" if is64bit else "poker-eval_x86"]
)
calc_prog = str(calc_prog[0])

if env["PLATFORM"].startswith("win"):
    fname = "calculator.bat"
    ftext = "@set PATH=%%PATH%%;%s\r\n" % env["LD_LIBRARY_PATH"]
    args = "%*"
elif env["PLATFORM"].startswith("darwin"):
    fname = "calculator.sh"
    ftext = (
        "#!/bin/sh\nexport DYLD_LIBRARY_PATH=%s:$LD_LIBRARY_PATH\n"
        % env["LD_LIBRARY_PATH"]
    )
    args = "$@"
else:
    fname = "calculator.sh"
    ftext = (
        "#!/bin/sh\nexport LD_LIBRARY_PATH=%s:$LD_LIBRARY_PATH\n"
        % env["LD_LIBRARY_PATH"]
    )
    args = "$@"

with open(os.path.abspath(fname), "w") as cmd:
    cmd.write(ftext)
    cmd.write("%s %s\n" % (os.path.abspath(calc_prog), args))

Execute(Chmod(os.path.abspath(fname), 0o755))
